### ISSUE TITLE
User Requirements Document (DEL-01)

### ISSUE THREAD

**Issue by handeerdem** [Open-EO/FuseTS#2]
From SoW REQ 5: Define User Requirements: 

 For the User Requirements a set of 3-5 use cases shall be defined. The selection of use cases shall be guided and warranted by the respective potential  for  improved  information  retrieval  when  employing  the  here developed data fusion and time series analytics methods. 

At  least  one  of  these  use  cases  shall  be  specifically  focussing  on  agriculture,  addressing  challenging  target  variables  (e.g.  crop  yield,  land  management  events,  crop  damage,  etc.).  Other  major  land domains shall be included such as forest, urban, grassland or water.  

Each use case shall define an end to end processing workflow starting with  EO  and  ancillary  source  data,  data  fusion  into  fused  data  stream(s),  time  series  modelling,  land  surface  characterisation  and  future   state   predictions.   Each   use   case   shall   be   developed   in   coordination with a domain expert (e.g. for agriculture, forestry, etc.). 

Develop and compile the User Requirements Document to guide the further development.

**Comment by mlubej** [comment]
Thank you @handeerdem for preparing the list of issues. I just noticed I didn't get any notifications because of the default settings. Perhaps it would be good to mention this on the channel so that we make sure everyone is tracking the important activity.

**Comment by mlubej** [comment]
The User Requirements Document is one the first deliverables that need to be prepared. I prepared a first draft of the plan how to go about it. It consists of 4 parts. More or less it's just an extraction from the tender, but I would still like some feedback if this is the direction into which we wish to proceed.

________

# Overview

## Part 1

The first part focuses on the 3 use cases we plan to work on (_land cover change detection, crop phenology indicators, agriculture and land management activity indicators_). Each use case is assigned to each partner based on the existing cooperations with clients. For each use case, the following will be prepared:
- a definition of an end-to-end workflow which is currently in place for the existing customer
- identification of potential improvements which can be implemented during the project
- a description of all necessary input data, either directly from the client (labels, auxiliary data, knowhow), or some derivatives of it
- a list of current needs and expectations of the client for the particular use case
  - what kind of results they expect, how good the results should be, how fast/frequently the results need to be delivered

## Part 2

In part 2 we will take what we have learned about the clients' needs and use it as a basis to prepare a survey in order to learn similar things from the wider community of users. The idea is to use this information to drive our development in a direction which is most useful to the community.

It's not clear at this point what the survey will look like and/or via which channels it will be distributed, but perhaps it's not so important to define it at this stage, since we require input from part 1 first.

## Part 3

Compiling the obtained information into a deliverable. Pretty straightforward and can more or less be done concurrently with parts 1 and 2.

## Part 4

In order to make sure that the software development meets the needs of end users, we should collect labels which will be used for validation. This can probably be something which is already currently used, or even something new, if we find a need for it. This part is not so much connected to the User Requirements Document, but it needs to be prepared as an input for the testing and validation phase of WP2.2.

_________________________

Let me know what you think of this outline.

**Comment by JochemV** [comment]
Hi Matic,
In Task 1, we have to work on SAR-Optical data fusion algorithm, a review on TS algorithms and quantiative analysis (see tasks WG1.1). I was wondering, does that part have to come into User Requirement Document, or is for elsewhere? We started to put material together in a document, but is perfectly fine it will be integrated elsewhere. Later we can discuss?

**Comment by mlubej** [comment]
> Hi Matic, In Task 1, we have to work on SAR-Optical data fusion algorithm, a review on TS algorithms and quantiative analysis (see tasks WG1.1). I was wondering, does that part have to come into User Requirement Document, or is for elsewhere? We started to put material together in a document, but is perfectly fine it will be integrated elsewhere. Later we can discuss?

Hi @JochemV!

I don't think this falls under the User Requirement Document, since this document is more focused on the needs and expectations of the client/end user. I do believe though that it has more to do with the System Requirements Document, so perhaps you should check with @jdries in #3. We can also discuss this privately if you want, feel free to ping me on MS Teams! :)

**Comment by jdries** [comment]
Proposal by @mlubej  seems quite fine, and indeed in line with what is suggested in the SOW REQ5 (copied that one in the description of this task)

Also agree that the result of the review should go in system requirements (DEL-02), as suggested by SOW REQ7:

> Specify the System Requirements based on and including key insights from the SotA review and the method evaluation, taking into account the defined User Requirements and requirements of this SOW. 
The System    Requirements    Document    shall    detail    the    scope    and    functionality of the data fusion and time series analytics frameworksin detail,  the required open source software development (modules, processes,  interfaces),  the  implementation  plan  for  the  on-demand, cloud-based   EO   service   provisioning   of   the   to   be   developed   frameworks.

**Comment by JochemV** [comment]
Hi Matic, 
Thanks for the update! We are maintaining some contact with our stakeholder (Itacyl). They are also interested in the project and I believe we can easily have a meeting with them or pass questions to them for serving the User Requierment Document. Just wondering, are you preparing some specific questions, or is it up to us to come wit questions? Earlier it was suggested: "what kind of results they expect, how good the results should be, how fast/frequently the results need to be delivered". Anything else? 
Please let us know and we will contact Itacyl. Thanks!

**Comment by mlubej** [comment]
Hi @JochemV!

> Just wondering, are you preparing some specific questions, or is it up to us to come wit questions? Earlier it was suggested: "what kind of results they expect, how good the results should be, how fast/frequently the results need to be delivered". Anything else? Please let us know and we will contact Itacyl. Thanks!

In order to ask concrete questions, we need to have a good understanding of the use case at hand, which means that the partners for the specific use case probably have the best idea what kind of questions are important/relevant. The ones proposed above serve just as a basic example and direction in which to aim. 

I will dump some concrete questions also in the ticket #47 during this week, perhaps that can also serve as a seed for finding further questions. However, I doubt that the questions alone will be enough to grasp the full picture of the specific use cases, this is why the proposed plan in https://github.com/Open-EO/FuseTS/issues/2#issuecomment-1050044411 was to prepare for each use case (by each partner) a description of the end-to-end workflow, either for the planned use-case, or for some similar use case already in place that a partner has with the stakeholder. Hopefully the draft for the use case about "Agriculture and land management activities identification" mentioned in https://github.com/Open-EO/FuseTS/issues/2#issuecomment-1087541531 will be a good starting point for others to use.

Additionally, I'm not so sure if we can/should aim for some finalized version of the survey to be ready and filled by the stakeholders, we might loose too much time this way. Sure, using whatever questions we have at hand is fine and we should definitely go for it, but I feel that limiting ourselves to the survey alone might mean that we will touch only the surface of the use case, so I feel that a verbal communication with the stakeholder about their needs and expectations related to the use case will uncover more of these details.

I hope I am making sense, please share your views or express your concerns, if you have any.

**Comment by JochemV** [comment]
Thanks for your inputs Matic!
Ok, I understand you. In that case we rather try to set up a meeting with the stakeholder later this week, and talk through the raised questions and discuss it further. 
Looking forward to see some concrete questions.
best, J.

**Comment by mlubej** [comment]
I have created a new folder and document for the deliverable DEL-01, based on the received template. It can be found [here](https://vitoresearch.sharepoint.com/:w:/r/sites/19730-ai4food-ProjectWorkspace-Consortium/Shared%20Documents/Project%20Workspace%20-%20Consortium/Deliverables/DEL-01/User%20Requirements%20Document/AI4FOOD_DEL_01_User_Requirements_Document.docx?d=w9c44d89ee5974ae8b3e007659f404776&csf=1&web=1&e=YsVLYi)

Please take a look and add the content for other use cases. Probably it might be a bit much for a start, but it can always be trimmed later.

**Comment by JochemV** [comment]
Hello Matic, 
Today we had a meeting with our stakeholder: ITACyL
We went through their wishes regarding the project. They also provided some background information. I hope this info serves the document. See here: https://docs.google.com/document/d/1QGyvlsS1pHVW_msgJn1Zz3JWmTp8bGmHdpSo2S-dJrM/edit?usp=sharing

**Comment by mlubej** [comment]
Hi @JochemV!

That's great to hear. I checked the document and it seems to contain the relevant information for the deliverable. Please organize among your team the conversion of the material and its addition to the [deliverable](https://vitoresearch.sharepoint.com/:w:/r/sites/19730-ai4food-ProjectWorkspace-Consortium/_layouts/15/Doc.aspx?sourcedoc=%7B9C44D89E-E597-4AE8-B3E0-07659F404776%7D&file=AI4FOOD_DEL_01_User_Requirements_Document.docx&action=default&mobileredirect=true) according to the steps in https://github.com/Open-EO/FuseTS/issues/2#issuecomment-1050044411. 

I would also kindly remind you about adding the use case specific questions to the survey. The link to the editable document can be found in MS teams (so that it's not shared here in public).

**Comment by jdries** [comment]
We have a stakeholder meeting tomorrow!
