### ISSUE TITLE
SRD-05 Multi-temporal outlier filter

### ISSUE THREAD

**Issue by jdries** [Open-EO/FuseTS#61]
Implement an outlier filter based on single pixel timeseries.
Should we also consider elimination of false positives, like Sentinel-2 flagging water as cloud?

**Comment by mlubej** [comment]
I had a bit of a look at this. I feel the scope of this issue is quite undefined:
- what kind of algorithm do we wish to apply?
- what kind of data are we working with?
- what kind of time-series are we working with (which use case)?

Already the 3 questions above make the scope of this issue explode. There was one article posted next to this issue which might come in handy: https://www.sciencedirect.com/science/article/pii/S0034425714002259 

But I don't believe that one to be useful, as it is targeted to Landsat, which we have never used before. I would suggest that if a user has a specific problem, the user implements their own outlier filter as a UDF, suitable to their problem, as opposed to us loosing time by providing different methods of outlier filtering as a preventive measure, not really being sure it would be used or not.

I would suggest going with something simple and generic, such as the z-score outlier filtering, which is basically quantitatively evaluating which points around the trend line are potential outliers, based on the size of the standard deviation from the mean. This is something intuitive and can be applied to take care of the occasional sharp spike.

**Comment by JanssenBrm** [comment]
As discussed during the meeting, the proposed approach is the preferred way to go.

**Comment by mlubej** [comment]
Changes implemented in https://github.com/Open-EO/FuseTS/pull/110

Proof of principle: 

![image](https://github.com/Open-EO/FuseTS/assets/37869250/347221e8-cc5f-428a-a9ae-b276de8a2ec4)

- Top image is raw time series (dummy NDVI) with outliers, along with the st.dev. band shown around the trend
- Middle image is z-score (standardised values), with bars shown as threshold values, and detected outliers shown in red
- Bottom image is the resulting filtered array, where outlier values were replaced with the trend values (mean)

**Comment by JanssenBrm** [comment]
@jdries , @GriffinBabe  - Can you review the changes?
