### ISSUE TITLE
Cannot execute Whittaker through openEO UDP

### ISSUE THREAD

**Issue by JanssenBrm** [Open-EO/FuseTS#78]
As part of WP5, we are setting up the different services as UDP's within openEO, allowing easy integration of the process within an existing workflow. To do this, I've created a separate branch where I added some code to publish the services as a UDP:
https://github.com/Open-EO/FuseTS/tree/openeo_publish 

To test the code, I've also created a corresponding notebook:
https://github.com/Open-EO/FuseTS/blob/openeo_publish/notebooks/UDP/AI4FOOD%20-%20Whittaker.ipynb 

However, when executing this notebook, I receive an error that seems to be related to the code in FuseTS:

<img width="679" alt="image" src="https://user-images.githubusercontent.com/10883374/234200903-c78b67d9-78f5-4990-ab20-277e26e7bd66.png">

**Comment by jdries** [comment]
It could be the value of smoothing lambda which is None here?

**Comment by JanssenBrm** [comment]
After some further investigation, it looks like the `context` in the UDF is empty. Even though we explicitly set some values (see https://github.com/Open-EO/FuseTS/blob/openeo_publish/src/fusets/openeo/services/publish_whittaker.py), the context seems to be empty in the UDF. 

@jdries  - Any idea why it behaves like this?

**Comment by soxofaan** [comment]
This usage pattern should now be fixed with the work from https://github.com/Open-EO/openeo-geopyspark-driver/issues/425

It is even covered by one of the cases of this parameterized unit test https://github.com/Open-EO/openeo-geopyspark-driver/blob/9f5c70ee1691593771440b89516dcf6f80159fe7/tests/test_api_result.py#L895-L1028

Feel free to reopen if there is still a problem. (Note that the fix is only on dev at the moment)
